exclude_patterns:
- "**/vendor/"
- "**/node_modules/"
- "**/data/"
- "config/"
- "dist/"
- "features/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/__tests__/"
- "Tests/"
- "**/*.d.ts"
- "**/*.spec.js"
- "**/*.test.js"
- "**/*.spec.ts"
- "**/*.test.ts"